[tool.bumpversion]
current_version = "0.1.8"  # Make sure this matches your current version
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
commit = true
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
message = "Bump version: {current_version} → {new_version}"
allow_dirty = true  # Add this line to allow bumping with uncommitted changes

[tool.bumpversion.file.pyproject.toml]
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

# If you have a __version__ in your package's __init__.py, uncomment and adjust these lines:
#[tool.bumpversion.file.src/dsk/__init__.py]
#search = '__version__ = "{current_version}"'
#replace = '__version__ = "{new_version}"'
